/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/setup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** First-run availability (true only while 0 organizations exist) */
    get: operations['getSetupState'];
    put?: never;
    /** Bootstrap the initial org + owner + workspace + starter project (FR-AUTH-010) */
    post: operations['bootstrap'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register (only when org allowPublicSignup=true; otherwise invite-only) (FR-AUTH-001) */
    post: operations['register'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email + password sign-in → access + rotating refresh (FR-AUTH-001/002) */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate the refresh token → new access + refresh; reuse revokes the family (FR-AUTH-002) */
    post: operations['refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke the current session/family (FR-AUTH-002) */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/verify-email': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Consume an EMAIL_VERIFY one-time token (FR-AUTH-003) */
    post: operations['verifyEmail'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/request-password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Request a password reset (uniform response — no enumeration, SC-010) (FR-AUTH-003) */
    post: operations['requestPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/request-verification': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Resend an email-verification link (uniform response — no enumeration, SC-010) (FR-AUTH-003) */
    post: operations['requestVerification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/confirm-password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Consume a PASSWORD_RESET token and set a new password (FR-AUTH-003) */
    post: operations['confirmPasswordReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current principal — user, org, role, scopes, accessible workspaces (FR-INT-MCP-001) */
    get: operations['whoami'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api-tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the caller's Personal Access Tokens (FR-AUTH-007) */
    get: operations['listApiTokens'];
    put?: never;
    /** Mint a PAT — secret returned ONCE (FR-AUTH-007, SC-012) */
    post: operations['createApiToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api-tokens/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a PAT (FR-AUTH-007) */
    delete: operations['revokeApiToken'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/orgs/current': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current organization + settings (FR-TEN-004) */
    get: operations['getCurrentOrg'];
    put?: never;
    post?: never;
    /** Soft-delete the organization (Owner only) (FR-RBAC-003, FR-TEN-006) */
    delete: operations['deleteOrg'];
    options?: never;
    head?: never;
    /** Update organization settings (Admin+) (FR-TEN-004) */
    patch: operations['updateOrgSettings'];
    trace?: never;
  };
  '/orgs/current/transfer-ownership': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Transfer ownership to another member (Owner only) (FR-RBAC-003) */
    post: operations['transferOwnership'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspaces in the org (FR-TEN-002) */
    get: operations['listWorkspaces'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/workspaces/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a workspace (FR-TEN-002) */
    get: operations['getWorkspace'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/memberships': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List members and their roles (FR-RBAC-001) */
    get: operations['listMemberships'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/memberships/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a member; revokes their sessions & tokens (Admin+) (FR-RBAC-001) */
    delete: operations['removeMember'];
    options?: never;
    head?: never;
    /** Change a member's role (Admin+; last-owner protected) (FR-RBAC-001) */
    patch: operations['setMemberRole'];
    trace?: never;
  };
  '/invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List pending invitations (FR-AUTH-011) */
    get: operations['listInvites'];
    put?: never;
    /** Invite by email or create a shareable link, with a pre-assigned role (Admin+) (FR-AUTH-011) */
    post: operations['createInvite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invites/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Preview an invitation (org name, role) before accepting (public) */
    get: operations['previewInvite'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invites/{token}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Accept an invitation → membership at the pre-assigned role (public, token-bearing) (FR-AUTH-011) */
    post: operations['acceptInvite'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/invites/{id}/_revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a pending invitation (Admin+) (FR-AUTH-011) */
    delete: operations['revokeInvite'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      code: string;
      message: string;
      details?: Record<string, never>;
    };
    SetupState: {
      /** @description true only while 0 orgs exist */
      available?: boolean;
    };
    BootstrapRequest: {
      organizationName: string;
      ownerName: string;
      /** Format: email */
      ownerEmail: string;
      /** Format: password */
      ownerPassword: string;
    };
    RegisterRequest: {
      name: string;
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    LoginRequest: {
      /** Format: email */
      email: string;
      /** Format: password */
      password: string;
    };
    RefreshRequest: {
      refreshToken: string;
    };
    TokenBody: {
      token: string;
    };
    EmailBody: {
      /** Format: email */
      email: string;
    };
    PasswordResetConfirm: {
      token: string;
      /** Format: password */
      newPassword: string;
    };
    AuthResult: {
      /** @description signed JWT */
      accessToken: string;
      /** @description opaque */
      refreshToken: string;
      /** @description access-token lifetime in seconds (<= 900) */
      expiresIn: number;
      user: components['schemas']['UserSummary'];
    };
    WhoAmI: {
      user: components['schemas']['UserSummary'];
      /** Format: uuid */
      organizationId: string;
      /** Format: uuid */
      activeWorkspaceId?: string | null;
      role: components['schemas']['Role'];
      /** @description PAT scopes (empty for UI sessions) */
      scopes: string[];
      workspaces?: components['schemas']['Workspace'][];
    };
    UserSummary: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      emailVerified: boolean;
    };
    /** @enum {string} */
    Role: 'OWNER' | 'ADMIN' | 'MEMBER' | 'GUEST' | 'VIEWER';
    ApiToken: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** @enum {string} */
      type?: 'PAT' | 'MCP';
      scopes?: string[];
      /** Format: date-time */
      lastUsedAt?: string | null;
      /** Format: date-time */
      expiresAt?: string | null;
      /** Format: date-time */
      createdAt?: string;
    };
    ApiTokenSecret: components['schemas']['ApiToken'] & {
      /** @description shown ONCE; store immediately (SC-002) */
      secret: string;
    };
    CreateApiToken: {
      name: string;
      /**
       * @default PAT
       * @enum {string}
       */
      type: 'PAT' | 'MCP';
      scopes?: string[];
      /** Format: date-time */
      expiresAt?: string | null;
    };
    Organization: {
      /** Format: uuid */
      id?: string;
      name?: string;
      slug?: string;
      settings?: components['schemas']['OrgSettings'];
    };
    OrgSettings: {
      /** @example America/New_York */
      timezone?: string;
      /** @example en-US */
      locale?: string;
      /** @enum {string} */
      weekStart?: 'SUNDAY' | 'MONDAY';
      workingDays?: number[];
      workingHours?: {
        start?: string;
        end?: string;
      };
      logoUrl?: string | null;
      /** @default false */
      allowPublicSignup: boolean;
    };
    TransferOwnership: {
      /** Format: uuid */
      toUserId: string;
      demoteSelfTo?: components['schemas']['Role'];
    };
    Workspace: {
      /** Format: uuid */
      id?: string;
      name?: string;
      slug?: string;
    };
    Membership: {
      /** Format: uuid */
      userId?: string;
      user?: components['schemas']['UserSummary'];
      role?: components['schemas']['Role'];
      /** Format: date-time */
      deactivatedAt?: string | null;
    };
    SetRole: {
      role: components['schemas']['Role'];
    };
    CreateInvite: {
      /**
       * Format: email
       * @description omit for a shareable-link invite
       */
      email?: string | null;
      role: components['schemas']['Role'];
      /** Format: uuid */
      workspaceId?: string | null;
      /** @default 168 */
      expiresInHours: number;
    };
    InvitationCreated: components['schemas']['Invitation'] & {
      /** @description shareable link (link invites) */
      acceptUrl?: string;
    };
    Invitation: {
      /** Format: uuid */
      id?: string;
      /** Format: email */
      email?: string | null;
      role?: components['schemas']['Role'];
      /** Format: uuid */
      invitedByUserId?: string | null;
      /** Format: date-time */
      expiresAt?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    InvitePreview: {
      organizationName?: string;
      role?: components['schemas']['Role'];
      /** Format: email */
      email?: string | null;
    };
    /** @description name+password required only when the invitee has no account yet */
    AcceptInvite: {
      name?: string;
      /** Format: password */
      password?: string;
    };
  };
  responses: {
    /** @description Validation error */
    Validation: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Authenticated but not permitted (default-deny */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Not found or cross-tenant (existence never leaked) */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: {
    IdPath: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getSetupState: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SetupState'];
        };
      };
    };
  };
  bootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BootstrapRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResult'];
        };
      };
      /** @description Already bootstrapped */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components['responses']['Validation'];
    };
  };
  register: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResult'];
        };
      };
      /** @description Public signup disabled */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Email already registered */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      422: components['responses']['Validation'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResult'];
        };
      };
      /** @description Invalid credentials (generic — no account-existence signal) */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Throttled / brute-force lockout (SC-011) */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResult'];
        };
      };
      /** @description Invalid/rotated/revoked refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  verifyEmail: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenBody'];
      };
    };
    responses: {
      /** @description Verified */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Expired or already used */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  requestPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailBody'];
      };
    };
    responses: {
      /** @description Accepted (always */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  requestVerification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailBody'];
      };
    };
    responses: {
      /** @description Accepted (always; no-op if unknown or already verified) */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  confirmPasswordReset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordResetConfirm'];
      };
    };
    responses: {
      /** @description Password changed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Expired or already used */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  whoami: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WhoAmI'];
        };
      };
      /** @description Unauthenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listApiTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiToken'][];
        };
      };
    };
  };
  createApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApiToken'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiTokenSecret'];
        };
      };
    };
  };
  revokeApiToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['IdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getCurrentOrg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'];
        };
      };
    };
  };
  deleteOrg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Soft-deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components['responses']['Forbidden'];
    };
  };
  updateOrgSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OrgSettings'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Organization'];
        };
      };
      403: components['responses']['Forbidden'];
    };
  };
  transferOwnership: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TransferOwnership'];
      };
    };
    responses: {
      /** @description Transferred */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components['responses']['Forbidden'];
      /** @description Target not an eligible member */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listWorkspaces: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workspace'][];
        };
      };
    };
  };
  getWorkspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['IdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Workspace'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  listMemberships: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Membership'][];
        };
      };
    };
  };
  removeMember: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      403: components['responses']['Forbidden'];
      /** @description Would remove the last Owner (SC-015) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  setMemberRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetRole'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Membership'];
        };
      };
      403: components['responses']['Forbidden'];
      /** @description Would remove the last Owner (SC-015) */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listInvites: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Invitation'][];
        };
      };
    };
  };
  createInvite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateInvite'];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitationCreated'];
        };
      };
    };
  };
  previewInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InvitePreview'];
        };
      };
      /** @description Expired */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  acceptInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['AcceptInvite'];
      };
    };
    responses: {
      /** @description Joined */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResult'];
        };
      };
      /** @description Expired */
      410: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  revokeInvite: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components['parameters']['IdPath'];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: components['responses']['NotFound'];
    };
  };
}
