/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List accessible projects */
    get: {
      parameters: {
        query?: {
          /** @description Opaque keyset cursor from pageInfo.nextCursor. */
          cursor?: components['parameters']['cursor'];
          limit?: components['parameters']['limit'];
          includeArchived?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['ProjectListEnvelope'];
      };
    };
    put?: never;
    /** Create a project (seeds default statuses + counter) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateProject'];
        };
      };
      responses: {
        201: components['responses']['ProjectEnvelope'];
        400: components['responses']['Error'];
        409: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components['parameters']['projectId'];
      };
      cookie?: never;
    };
    /** Get a project */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['ProjectEnvelope'];
        403: components['responses']['Error'];
        404: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    /** Delete a project (cascade) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update / archive / restore a project */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProject'];
        };
      };
      responses: {
        200: components['responses']['ProjectEnvelope'];
      };
    };
    trace?: never;
  };
  '/projects/{projectId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components['parameters']['projectId'];
      };
      cookie?: never;
    };
    /** List project members */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Members */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MemberListEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Add a member */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['AddMember'];
        };
      };
      responses: {
        /** @description Added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        403: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{projectId}/statuses': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components['parameters']['projectId'];
      };
      cookie?: never;
    };
    /** List statuses (board columns, ordered) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Statuses */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StatusListEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Add a status (mapped to a category) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateStatus'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/projects/{projectId}/statuses/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        projectId: components['parameters']['projectId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder statuses */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: components['parameters']['projectId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            orderedIds: string[];
          };
        };
      };
      responses: {
        /** @description Reordered */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/statuses/{statusId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        statusId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a status (requires reassignTo if it has items) */
    delete: {
      parameters: {
        query?: {
          /** @description Target status to re-map existing items to. Required when the status has items. */
          reassignTo?: string;
        };
        header?: never;
        path: {
          statusId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        409: components['responses']['Error'];
      };
    };
    options?: never;
    head?: never;
    /** Rename / recolor / recategorize a status */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          statusId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/work-items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List / filter work items (powers List, Board, smart views)
     * @description Accepts the filter AST (see filter-dsl.md) as a base64-encoded `filter` param OR typed shorthand params. Cursor (keyset) pagination. `group` + `sort` per filter-dsl.md.
     */
    get: {
      parameters: {
        query?: {
          /** @description Omit for cross-project (My Work). */
          projectId?: string;
          /** @description base64(JSON filter AST). */
          filter?: string;
          /** @description Live smart view (FR-VIEW-009 */
          smart?: 'my-issues' | 'due-soon' | 'overdue' | 'urgent' | 'my-work';
          group?: 'status' | 'assignee' | 'priority' | 'label' | 'project';
          /** @description Comma list, e.g. -priority,due_date (multi-key). */
          sort?: string;
          /** @description Opaque keyset cursor from pageInfo.nextCursor. */
          cursor?: components['parameters']['cursor'];
          limit?: components['parameters']['limit'];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['WorkItemListEnvelope'];
      };
    };
    put?: never;
    /**
     * Create a work item (title-only or quick-add inline syntax)
     * @description `title` alone creates with project defaults (FR-WI-001). If `quickAdd` is provided, the server parses `@assignee #label !priority ^date` into structured fields and returns any `unresolved` tokens (FR-WI-004). Mints a never-recycled per-project key (FR-WI-002).
     */
    post: {
      parameters: {
        query?: never;
        header?: {
          'Idempotency-Key'?: components['parameters']['idempotencyKey'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWorkItem'];
        };
      };
      responses: {
        201: components['responses']['WorkItemEnvelope'];
        400: components['responses']['Error'];
        403: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    /** Get a work item (full payload incl. labels, watchers, child count) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['WorkItemEnvelope'];
        404: components['responses']['Error'];
      };
    };
    put?: never;
    post?: never;
    /** Soft-delete (trash) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Trashed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update fields (logs activity per changed field)
     * @description Optimistic concurrency via `version`; stale → 409 (FR-WI-009).
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateWorkItem'];
        };
      };
      responses: {
        200: components['responses']['WorkItemEnvelope'];
        409: components['responses']['Error'];
      };
    };
    trace?: never;
  };
  '/work-items/{itemId}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore from trash */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['WorkItemEnvelope'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/move': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Move on board (change status and/or position)
     * @description Single-row fractional reorder; logs a STATUS_CHANGED/MOVED activity entry (FR-VIEW-001).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['MoveWorkItem'];
        };
      };
      responses: {
        200: components['responses']['WorkItemEnvelope'];
        409: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/assign': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Assign / unassign (single assignee in M1) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** Format: uuid */
            assigneeId?: string | null;
          };
        };
      };
      responses: {
        200: components['responses']['WorkItemEnvelope'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/labels': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a label (by id or name; create-on-capture per policy) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            labelId?: string;
            name?: string;
          };
        };
      };
      responses: {
        /** @description Labeled */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/labels/{labelId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
        labelId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove a label */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
          labelId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/subtasks': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    /** List child sub-tasks */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['WorkItemListEnvelope'];
      };
    };
    put?: never;
    /** Create a sub-task under this item (cycle/depth checked) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateWorkItem'];
        };
      };
      responses: {
        201: components['responses']['WorkItemEnvelope'];
        422: components['responses']['Error'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/activity': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    /** Per-item activity / history feed */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Activity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ActivityListEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/work-items/{itemId}/comments': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        itemId: components['parameters']['itemId'];
      };
      cookie?: never;
    };
    /** List threaded comments */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Comments */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommentListEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Post a comment (markdown; @mentions notify + grant context access) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          itemId: components['parameters']['itemId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateComment'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CommentEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/labels': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List workspace labels */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Labels */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LabelListEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Create a label */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            color?: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/views': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List saved views (personal + shared) for a project or cross-project */
    get: {
      parameters: {
        query?: {
          projectId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Views */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ViewListEnvelope'];
          };
        };
      };
    };
    put?: never;
    /** Save a view (personal by default; shared if scope=SHARED) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['SaveView'];
        };
      };
      responses: {
        /** @description Saved */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ViewEnvelope'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/views/{viewId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        viewId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a saved view */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          viewId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a saved view */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          viewId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        200: components['responses']['ProjectEnvelope'];
      };
    };
    trace?: never;
  };
  '/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Full-text search (items, comments, projects, labels, users), tenant + permission scoped */
    get: {
      parameters: {
        query: {
          q: string;
          /** @description Comma list: work_item,comment,project,label,user */
          types?: string;
          limit?: components['parameters']['limit'];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ranked, scoped results */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SearchEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Inbox (filter by state) */
    get: {
      parameters: {
        query?: {
          state?: 'unread' | 'all' | 'snoozed' | 'archived';
          /** @description Opaque keyset cursor from pageInfo.nextCursor. */
          cursor?: components['parameters']['cursor'];
          limit?: components['parameters']['limit'];
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Inbox */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['NotificationListEnvelope'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/unread-count': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Unread count (badge) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Count */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: {
                count?: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/{notificationId}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        notificationId: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Mark read/unread, snooze, or archive */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          notificationId: string;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            read?: boolean;
            /** Format: date-time */
            snoozedUntil?: string | null;
            archived?: boolean;
          };
        };
      };
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PageInfoEnvelope: {
      pageInfo?: {
        nextCursor?: string | null;
        hasNextPage?: boolean;
      };
    };
    ErrorEnvelope: {
      error: string;
      statusCode: number;
      message: string[];
      /** Format: date-time */
      timestamp: string;
      path: string;
    };
    Project: {
      /** Format: uuid */
      id?: string;
      name?: string;
      keyPrefix?: string;
      description?: string | null;
      icon?: string | null;
      color?: string;
      /** Format: uuid */
      leadId?: string | null;
      /** Format: date-time */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt?: string;
    };
    CreateProject: {
      name: string;
      keyPrefix: string;
      description?: string;
      icon?: string;
      color?: string;
      /** Format: uuid */
      leadId?: string;
    };
    UpdateProject: {
      name?: string;
      description?: string;
      icon?: string;
      color?: string;
      /** Format: uuid */
      leadId?: string | null;
      archived?: boolean;
    };
    AddMember: {
      /** Format: uuid */
      userId: string;
      /**
       * @default MEMBER
       * @enum {string}
       */
      role: 'ADMIN' | 'MEMBER' | 'VIEWER';
    };
    MemberListEnvelope: components['schemas']['PageInfoEnvelope'] & {
      data?: {
        /** Format: uuid */
        userId?: string;
        role?: string;
        name?: string;
      }[];
    };
    Status: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** @enum {string} */
      category?: 'BACKLOG' | 'UNSTARTED' | 'STARTED' | 'COMPLETED' | 'CANCELLED';
      color?: string;
      position?: number;
    };
    CreateStatus: {
      name: string;
      /** @enum {string} */
      category: 'BACKLOG' | 'UNSTARTED' | 'STARTED' | 'COMPLETED' | 'CANCELLED';
      color?: string;
      position?: number;
    };
    StatusListEnvelope: {
      data?: components['schemas']['Status'][];
    };
    WorkItem: {
      /** Format: uuid */
      id?: string;
      /** @description Derived display key, e.g. RY-142 */
      key?: string;
      number?: number;
      /** Format: uuid */
      projectId?: string;
      title?: string;
      description?: string | null;
      /** Format: uuid */
      statusId?: string;
      /** @enum {string} */
      priority?: 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE';
      /** Format: uuid */
      assigneeId?: string | null;
      /** Format: uuid */
      reporterId?: string | null;
      /** Format: uuid */
      parentId?: string | null;
      childCount?: number;
      labelIds?: string[];
      estimateValue?: number | null;
      /** Format: date */
      startDate?: string | null;
      /** Format: date */
      endDate?: string | null;
      /** Format: date */
      dueDate?: string | null;
      /** @description Computed: dueDate<today(orgTz) and not in a COMPLETED/CANCELLED status */
      overdue?: boolean;
      position?: number | null;
      version?: number;
      /** Format: date-time */
      completedAt?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    CreateWorkItem: {
      /**
       * Format: uuid
       * @description Required at /work-items; implied at /subtasks.
       */
      projectId?: string;
      title?: string;
      /** @description Raw quick-add line; server parses @ # ! ^ tokens (FR-WI-004). */
      quickAdd?: string;
      description?: string;
      /** Format: uuid */
      statusId?: string;
      /** @enum {string} */
      priority?: 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE';
      /** Format: uuid */
      assigneeId?: string;
      labelIds?: string[];
      /** Format: uuid */
      parentId?: string;
      estimateValue?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      /** Format: date */
      dueDate?: string;
    } & (unknown | unknown);
    UpdateWorkItem: {
      /** @description Expected current version (optimistic lock). */
      version: number;
      title?: string;
      description?: string;
      /** @enum {string} */
      priority?: 'URGENT' | 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE';
      /** Format: uuid */
      assigneeId?: string | null;
      /** Format: uuid */
      parentId?: string | null;
      estimateValue?: number | null;
      /** Format: date */
      startDate?: string | null;
      /** Format: date */
      endDate?: string | null;
      /** Format: date */
      dueDate?: string | null;
    };
    MoveWorkItem: {
      version: number;
      /** Format: uuid */
      statusId?: string;
      /**
       * Format: uuid
       * @description Place before this sibling (fractional rank).
       */
      beforeId?: string;
      /**
       * Format: uuid
       * @description Place after this sibling.
       */
      afterId?: string;
    };
    CreateWorkItemResponseMeta: {
      /** @description Quick-add tokens that could not be resolved (surfaced, never dropped — FR-WI-004). */
      unresolved?: {
        token?: string;
        /** @enum {string} */
        kind?: 'assignee' | 'label' | 'priority' | 'date';
      }[];
    };
    Comment: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      workItemId?: string;
      /** Format: uuid */
      authorId?: string;
      /** Format: uuid */
      parentId?: string | null;
      body?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      editedAt?: string | null;
    };
    CreateComment: {
      body: string;
      /** Format: uuid */
      parentId?: string;
    };
    CommentEnvelope: {
      data?: components['schemas']['Comment'];
    };
    CommentListEnvelope: components['schemas']['PageInfoEnvelope'] & {
      data?: components['schemas']['Comment'][];
    };
    Label: {
      /** Format: uuid */
      id?: string;
      name?: string;
      color?: string;
    };
    LabelListEnvelope: {
      data?: components['schemas']['Label'][];
    };
    SaveView: {
      name: string;
      /** @enum {string} */
      kind: 'BOARD' | 'LIST';
      /**
       * @default PERSONAL
       * @enum {string}
       */
      scope: 'PERSONAL' | 'SHARED';
      /** Format: uuid */
      projectId?: string | null;
      /** @description Filter AST (filter-dsl.md). */
      filters?: Record<string, never>;
      grouping?: Record<string, never>;
      sort?: Record<string, never>[];
      layout?: Record<string, never>;
    };
    View: components['schemas']['SaveView'] & {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      ownerId?: string;
    };
    ViewEnvelope: {
      data?: components['schemas']['View'];
    };
    ViewListEnvelope: {
      data?: components['schemas']['View'][];
    };
    ActivityEntry: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      actorId?: string | null;
      action?: string;
      field?: string | null;
      oldValue?: unknown;
      newValue?: unknown;
      /** Format: date-time */
      createdAt?: string;
    };
    ActivityListEnvelope: components['schemas']['PageInfoEnvelope'] & {
      data?: components['schemas']['ActivityEntry'][];
    };
    SearchResult: {
      /** @enum {string} */
      type?: 'work_item' | 'comment' | 'project' | 'label' | 'user';
      /** Format: uuid */
      id?: string;
      title?: string;
      snippet?: string | null;
      rank?: number;
      /** Format: uuid */
      projectId?: string | null;
    };
    SearchEnvelope: {
      data?: components['schemas']['SearchResult'][];
    };
    Notification: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      type?: 'ASSIGNED' | 'MENTIONED' | 'COMMENTED' | 'STATUS_CHANGED' | 'DUE_SOON' | 'OVERDUE';
      entityType?: string;
      /** Format: uuid */
      entityId?: string;
      /** Format: uuid */
      actorId?: string | null;
      payload?: Record<string, never>;
      /** Format: date-time */
      readAt?: string | null;
      /** Format: date-time */
      snoozedUntil?: string | null;
      /** Format: date-time */
      archivedAt?: string | null;
      /** Format: date-time */
      createdAt?: string;
    };
    NotificationListEnvelope: components['schemas']['PageInfoEnvelope'] & {
      data?: components['schemas']['Notification'][];
    };
  };
  responses: {
    /** @description Error envelope */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description A project */
    ProjectEnvelope: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          statusCode?: number;
          message?: string;
          data?: components['schemas']['Project'];
        };
      };
    };
    /** @description Projects page */
    ProjectListEnvelope: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['PageInfoEnvelope'] & {
          data?: components['schemas']['Project'][];
        };
      };
    };
    /** @description A work item */
    WorkItemEnvelope: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': {
          statusCode?: number;
          message?: string;
          data?: components['schemas']['WorkItem'];
        };
      };
    };
    /** @description Work items page */
    WorkItemListEnvelope: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['PageInfoEnvelope'] & {
          data?: components['schemas']['WorkItem'][];
        };
      };
    };
  };
  parameters: {
    projectId: string;
    itemId: string;
    /** @description Opaque keyset cursor from pageInfo.nextCursor. */
    cursor: string;
    limit: number;
    idempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
